---
title: "BSB brothers | Metal Stamping"
---

<br>B.S. Brothers offers a wide range of Metal Stamping services from simple blanking tools to complex progressive die stamping. Along with in-house designing and engineering of custom dies, we also repair, maintain, and run existing dies. We have the ability to stamp most materials including heat-resistant abrasive alloys, ferrous or non-ferrous alloys, and countless exotic metals. 

With over 25 years in the Metal Stamping industry, we specialize in high precision cost-effective solutions to exact tolerances. Whether you’re looking for prototype samples or small volume orders or long run cost effective stamping solutions, we can manufacture your custom parts and components. We also provide a variety of value-added services including Degreasing, Packaging, Assembly/Sub-Assembly, and more. 

From our Quality Assurance to our fast turnaround, we are an established leader in Metal Stamping. When you invest in a new die built by NHS, you will never be billed for die maintenance again. NHS maintains your die for the life of the project at no additional cost to you. This is just one example of our integrity and customer commitment. Another example is our expert engineers who work closely with you at any stage of the manufacturing process to determine the optimal strategy for your needs. 

We appreciate your patronage. Please contact us to learn how we can help you with your project.
<br><br>