---
title: "Materials"
---

<br>B. S. Brothers has the ability to handle a wide range of materials. We provide precision Metal Stampings for a variety of industries and applications -- from micro-miniature parts made with very thin material, to the strongest steel components required by the automotive Industry. 

We specialize in quick turnaround Precision Metal Stamping of heat-resistant metal alloys, ferrous, nonferrous, and countless exotic metals. We also offer value-added assembly for small volume and prototype orders. 

If you do not see your material listed below, please call us or fill out our free quote form.

Materials We Use... 
<br>
<ul>
<br><li>Stock thickness ranges from .0015 to .185+ </li>
<li>Stock width ranges from 1/4" up to 12"</li>
<li>Ferrous and non-ferrous</li>
<li>Cobalt, Galvanized & Spring Steel</li>
<li>Steel</li>
<li>Stainless Steel</li>
<li>Copper</li>
<li>Brass</li>
<li>Aluminum</li>
<li>Titanium</li>
<li>Preplated Materials</li>
<li>Mylar</li>
<li>Fibre</li>
<li>Foil</li>
<li>Mica</li>
<li>and more...</li>
</ul>
<br>